app = 'jellyfin-manuel'
primary_region = 'fra'

[processes]
  app = "/usr/lib/jellyfin/bin/jellyfin --datadir /config/data --cachedir /config/cache --ffmpeg /usr/lib/jellyfin-ffmpeg/ffmpeg"--datadir /config/data --cachedir /config/cache --ffmpeg /usr/lib/jellyfin-ffmpeg/ffmpeg"

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[services]]
  internal_port = 8096
  protocol = "tcp"
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    interval = "0s"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[mounts]
  source = "jellyfin_data"
  destination = "/config"
