app = 'jellyfin-manuel'
primary_region = 'fra'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[services]]
  internal_port = 8096
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[mounts]
  source = "jellyfin_data"
  destination = "/config"
